name: cil_testenv
channels:
  - anaconda
  - pytorch
  - defaults
dependencies:
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2023.05.30
  - ffmpeg=4.3
  - freetype=2.12.1
  - gettext=0.21.0
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - icu=58.2
  - intel-openmp=2023.1.0
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - lerc=3.0
  - libcxx=14.0.6
  - libdeflate=1.17
  - libffi=3.4.4
  - libiconv=1.16
  - libidn2=2.3.4
  - libpng=1.6.39
  - libtasn1=4.19.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libuv=1.44.2
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxml2=2.10.3
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.6
  - mkl_random=1.2.2
  - ncurses=6.4
  - nettle=3.7.3
  - numpy=1.23.5
  - numpy-base=1.23.5
  - openh264=2.1.1
  - openssl=3.0.8
  - pillow=9.4.0
  - pip=23.1.2
  - python=3.8.16
  - pytorch=1.10.1
  - readline=8.2
  - setuptools=67.8.0
  - sqlite=3.41.2
  - tbb=2021.8.0
  - tk=8.6.12
  - torchaudio=0.10.1=py38_cpu
  - torchvision=0.11.2=py38_cpu
  - typing_extensions=4.6.3
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - albumentations==1.3.1
    - appdirs==1.4.4
    - certifi==2023.5.7
    - charset-normalizer==3.1.0
    - click==8.1.3
    - docker-pycreds==0.4.0
    - efficientnet-pytorch==0.7.1
    - filelock==3.12.2
    - fsspec==2023.6.0
    - gitdb==4.0.10
    - gitpython==3.1.31
    - huggingface-hub==0.15.1
    - idna==3.4
    - imageio==2.31.1
    - joblib==1.2.0
    - lazy-loader==0.2
    - munch==3.0.0
    - networkx==3.1
    - opencv-python==4.7.0.72
    - opencv-python-headless==4.7.0.72
    - packaging==23.1
    - pathtools==0.1.2
    - pretrainedmodels==0.7.4
    - protobuf==4.23.3
    - psutil==5.9.5
    - pywavelets==1.4.1
    - pyyaml==6.0
    - qudida==0.0.4
    - requests==2.31.0
    - safetensors==0.3.1
    - scikit-image==0.21.0
    - scikit-learn==1.2.2
    - scipy==1.10.1
    - segmentation-models-pytorch==0.3.3
    - sentry-sdk==1.25.1
    - setproctitle==1.3.2
    - six==1.16.0
    - smmap==5.0.0
    - threadpoolctl==3.1.0
    - tifffile==2023.4.12
    - timm==0.9.2
    - tqdm==4.65.0
    - urllib3==2.0.3
    - wandb==0.15.4
    - yacs==0.1.8

