log_level   : INFO
log_dir    : /home/ivan/PycharmProjects/ETH/road-segmentation-ethz-cil-2023/results
data :
  root_dir : /home/ivan/PycharmProjects/ETH/road-segmentation-ethz-cil-2023/src/output/log

test :
  test_path : /home/ivan/PycharmProjects/ETH/road-segmentation-ethz-cil-2023/data/test/images
  mask_results_path : /home/ivan/PycharmProjects/ETH/road-segmentation-ethz-cil-2023/src/output/results_new
  submission_path : /home/ivan/PycharmProjects/ETH/road-segmentation-ethz-cil-2023/src/output/ivan_be_running_baby_2023-07-05__19-38-12/submission/test_submit.csv
  model_path : /home/ivan/PycharmProjects/ETH/road-segmentation-ethz-cil-2023/src/output/ivan_be_running_baby_2023-07-05__19-38-12/100.pth
  device : 'cpu'
  stride: 50