seed        : 42
Fixes onnum_workers : 8
log_level   : INFO
log_dir    : /home/ivan/PycharmProjects/ETH/road-segmentation-ethz-cil-2023/src/output
data :
  root_dir : /home/ivan/PycharmProjects/ETH/road-segmentation-ethz-cil-2023/data/seg-data

train :
  batch_size : 256
  log_every  : 100
  save_every : 1
  epochs     : 100

wandb:
  wandb: false
  entity: "cil-road-seg-2023"
  project: "trial"
  name: "ivan_be_running_baby"
  group: null
  id : "ivan_be_running_baby"