seed        : 42
num_workers : 4
log_level   : INFO
log_dir    : /home/ivan/PycharmProjects/ETH/road-segmentation-ethz-cil-2023/src/output
data :
  root_dir : /home/ivan/PycharmProjects/ETH/road-segmentation-ethz-cil-2023/data/seg-data

train :
  batch_size : 32
  log_every  : 50
  save_every : 1
  epochs: 100

validation:
  batch_size: 32
  valid_every: 1

model:
  # resnet50, efficientnet-b4, xception, inceptionv4, mobilenet_v2
  encoder: 'resnet101' #resnet50, efficientnet-b3, resnet34, densenet169, xception, inceptionv4, mobilenet_v2, vgg16

loss:
  loss_type: ["ce+ftl"] #["ce"] #options: ce, dice, ftl, ce+dice, ce+ftl
  epochs: [100] #[5]
  wlambda: [0.5] #[0.5]
  alpha: [0.7] #[0.7]
  gamma: [1.5] #[1.5]

wandb:
  wandb: true
  entity: "cil-road-seg-2023"
  project: "trial"
  name: "unet_resnet101_ce+ftl"
  group: null
  id : "unet_resnet101_ce+ftl"