log_level   : INFO
log_dir    : /home/ivan/PycharmProjects/ETH/road-segmentation-ethz-cil-2023/results
data :
  root_dir : /home/ivan/PycharmProjects/ETH/road-segmentation-ethz-cil-2023/src/output/log

test :
  test_path : /home/ivan/PycharmProjects/ETH/road-segmentation-ethz-cil-2023/data/test/images
  mask_results_path : /home/ivan/PycharmProjects/ETH/road-segmentation-ethz-cil-2023/src/output/results_ensemble
  submission_path : /home/ivan/PycharmProjects/ETH/road-segmentation-ethz-cil-2023/src/output/results_ensemble/test_submit_ensemble.csv
  model_ensemble_name: ['efficientnet-b3', 'efficientnet-b3', 'mobilenet_v2', 'resnet34'] #efficientnet-b3, resnet34, densenet169, xception, mobilenet_v2, vgg16
  model_ensemble_path : ['/home/ivan/Downloads/ce_ftl_100.pth', '/home/ivan/PycharmProjects/ETH/road-segmentation-ethz-cil-2023/src/output/efficientnet-b3+ftl_2023-07-17__20-27-03/100.pth', '/home/ivan/PycharmProjects/ETH/road-segmentation-ethz-cil-2023/src/output/mobilenet_v2_ce+ftl_2023-07-17__19-59-16/100.pth', '/home/ivan/PycharmProjects/ETH/road-segmentation-ethz-cil-2023/src/output/resnet34+ftl_2023-07-17__20-53-55/100.pth'] #list of the model paths corresponding to the above ensemble_name order
  device : 'cuda'
  stride: 32
  auto_padding: True
  padding: 0
