log_level   : INFO
log_dir    : /home/ivan/PycharmProjects/ETH/road-segmentation-ethz-cil-2023/results
data :
  root_dir : /home/ivan/PycharmProjects/ETH/road-segmentation-ethz-cil-2023/src/output/log

test :
  test_path : /home/ivan/PycharmProjects/ETH/road-segmentation-ethz-cil-2023/data/test/images
  mask_results_path : /home/ivan/PycharmProjects/ETH/road-segmentation-ethz-cil-2023/src/output/results_256
  submission_path : /home/ivan/PycharmProjects/ETH/road-segmentation-ethz-cil-2023/src/output/SAM_fine_tune_no_validation_2023-07-16__11-42-06/submission/sam_submit_stride_256.csv
  model_path : /home/ivan/PycharmProjects/ETH/road-segmentation-ethz-cil-2023/src/output/SAM_fine_tune_no_validation_2023-07-16__11-42-06/5.pth
  device : 'cuda'
  stride: 256
  auto_padding: True
  padding: 0
