log_level   : INFO
log_dir    : /home/ivan/PycharmProjects/ETH/road-segmentation-ethz-cil-2023/results
data :
  root_dir : /home/ivan/PycharmProjects/ETH/road-segmentation-ethz-cil-2023/src/output/log

test :
  test_path : /home/ivan/PycharmProjects/ETH/road-segmentation-ethz-cil-2023/data/kaggle-data/test/images
  mask_results_path : /home/ivan/PycharmProjects/ETH/road-segmentation-ethz-cil-2023/src/output/results_30k
  submission_path : /home/ivan/PycharmProjects/ETH/road-segmentation-ethz-cil-2023/src/output/results_30k/test_submit_stride_256.csv
  model_path : /home/ivan/PycharmProjects/ETH/road-segmentation-ethz-cil-2023/src/output/30K_xception_ce_2023-07-28__02-09-41/100.pth
  device : 'cuda'
  stride: 256
  auto_padding: True
  padding: 0
