seed        : 42
num_workers : 4
log_level   : INFO
log_dir    : '/media/ankitaghosh/Data/ETH/CIL/project/experiments/' 
data :
  root_dir : /media/ankitaghosh/Data/ETH/CIL/project/seg-data

train :
  batch_size : 4
  log_every  : 1
  save_every : 1
  epochs: 5

validation:
  batch_size: 4
  valid_every: 1

model:
  encoder: 'mobilenet_v2' #efficientnet-b3, resnet34, densenet169, xception, mobilenet_v2, vgg16

loss:
  loss_type: ["ce+ftl"] #["ce"] #options: ce, dice, ftl, ce+dice, ce+ftl
  epochs: [100] #[5]
  wlambda: [0.5] #[0.5]
  alpha: [0.7] #[0.7]
  gamma: [1.5] #[1.5]

wandb:
  wandb: true
  entity: "cil-road-seg-2023"
  project: "trial"
  name: "trial_run_multiloss"
  group: null
  id : "trial_run_multiloss"