log_level   : INFO
log_dir    : /home/ivan/PycharmProjects/ETH/road-segmentation-ethz-cil-2023/results
data :
  root_dir : /home/ivan/PycharmProjects/ETH/road-segmentation-ethz-cil-2023/src/output/log

test :
  test_path : /home/ivan/PycharmProjects/ETH/road-segmentation-ethz-cil-2023/data/test/images
  mask_results_path : /home/ivan/PycharmProjects/ETH/road-segmentation-ethz-cil-2023/src/output/results_256
  submission_path : /home/ivan/PycharmProjects/ETH/road-segmentation-ethz-cil-2023/src/output/ivan_be_running_baby_2023-07-05__19-38-12/submission/test_submit_stride_256.csv
  model_ensemble_name: ['list of names of encoders'] #efficientnet-b3, resnet34, densenet169, xception, mobilenet_v2, vgg16
  model_ensemble_path : ['/home/ivan/Downloads/ce_ftl_100.pth'] #list of the model paths corresponding to the above ensemble_name order
  device : 'cuda'
  stride: 256
  auto_padding: True
  padding: 0
