seed        : 42
num_workers : 4
log_level   : INFO
log_dir    : '' 
data :
  root_dir :/home/ivan/PycharmProjects/ETH/road-segmentation-ethz-cil-2023/data/seg-data
train :
  batch_size : 8
  log_every  : 50
  save_every : 1

wandb:
  wandb: false
  entity: ""
  project: ""
  name: ""
  group: null
  id : null