seed        : 42
num_workers : 4
log_level   : INFO
log_dir    : /local/home/sdebsarkar/Documents/code/course-projects/road-segmentation-ethz-cil-2023/src/output_ce_dice
data :
  root_dir : /media/sdebsarkar/extra-hdd/datasets/cil-road-seg-data/seg-data

train :
  batch_size : 8
  log_every  : 100
  save_every : 1
  epochs     : 100

wandb:
  wandb: true
  entity: "cil-road-seg-2023"
  project: "trial"
  name: "ce+dice"
  group: null
  id : "ce+dice"

loss:
  loss_type: "ce+dice" #options: ce, dice, ftl, ce+dice, ce+ftl
  wlambda: 0.5
  alpha: 0.7
  gamma: 1.5